export const DEFAULT_BOARD_LABEL_DATA = [
    {
        label_public_id: 'default',
        label_title: 'Nova Tarefa',
        priority_public_id: 'default',
        priority_tag: 'Sem Prioridade',
        priority_color: '#cccccc',
        task_public_id: 'default',
        task_description: 'TESTE0',
        task_starts_in: new Date().toISOString(),
        task_expires_in: new Date().toISOString(),
    },
    {
        label_public_id: 'default01',
        label_title: 'Em Progresso',
        priority_public_id: 'default',
        priority_tag: 'Sem Prioridade',
        priority_color: '#cccccc',
        task_public_id: 'default',
        task_description: 'TESTE0',
        task_starts_in: new Date().toISOString(),
        task_expires_in: new Date().toISOString(),
    },
    {
        label_public_id: 'default03',
        label_title: 'Em Espera',
        priority_public_id: 'default',
        priority_tag: 'Sem Prioridade',
        priority_color: '#cccccc',
        task_public_id: 'default',
        task_description: 'TESTE0',
        task_starts_in: new Date().toISOString(),
        task_expires_in: new Date().toISOString(),
    },
    {
        label_public_id: 'default04',
        label_title: 'Finalizada',
        priority_public_id: 'default',
        priority_tag: 'Sem Prioridade',
        priority_color: '#cccccc',
        task_public_id: 'default',
        task_description: 'TESTE0',
        task_starts_in: new Date().toISOString(),
        task_expires_in: new Date().toISOString(),
    }
]